default_colors:
  type: table
  description: Stores default colors.
  fields:
    id:
      type: serial
      unsigned: true
      not null: true
    name:
      type: varchar
      length: 255
      not null: true
    hexadecimal:
      type: varchar
      length: 6 #RRGGBB
      not null: true
    # rgb_value:  // *GET* THIS ONLY just in time but no need to store
      # type: varchar
      # length: 255
    css_variable: # LightGoldenRodYellow / $your-brand-name-color
      type: varchar
      length: 255
    description:
      type: text
  primary key:
    - id
